YunPan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'YunPan'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload_file, name='upload'),
    path('public/', views.public, name='public'),
    path('private/', views.private, name='private'),
    path('file/<int:pk>/', views.download_file, name='file'),
    path('download/<int:pk>/', views.download_private_file, name='download'),
    path('move/<int:pk>/', views.change_file_type, name='move'),
    path('delete/<int:pk>/', views.delete_file, name='delete'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yun/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('YunPan.urls')),
    path('admin/', admin.site.urls),
]

YunPan/models.py
from django.db import models
from django.contrib.auth import get_user_model


def upload_path(instance, filename):
    if instance.file_type == 'media':
        path = 'media'
    else:
        path = str(instance.user.id)
    return '{0}/{1}'.format(path, filename)


class UploadFile(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)  # 所属用户
    upload = models.FileField(upload_to=upload_path)

    file_type_choices = (
        ('private', '私有文件'),
        ('public', '公共文件'),
        ('media', '媒体文件')
    )
    file_type = models.CharField(max_length=15, choices=file_type_choices, default=file_type_choices[0][0])  # 文件类型

    upload_time = models.DateTimeField(auto_now=True)  # 上传时间


ContentType = {
    "*": "application/octet-stream",
    "tif": "application/x-tif",
    "001": "application/x-001",
    "301": "application/x-301",
    "323": "text/h323",
    "906": "application/x-906",
    "907": "drawing/907",
    "a11": "application/x-a11",
    "acp": "audio/x-mei-aac",
    "ai": "application/postscript",
    "aif": "audio/aiff",
    "aifc": "audio/aiff",
    "aiff": "audio/aiff",
    "anv": "application/x-anv",
    "asa": "text/asa",
    "asf": "video/x-ms-asf",
    "asp": "text/asp",
    "asx": "video/x-ms-asf",
    "au": "audio/basic",
    "avi": "video/avi",
    "awf": "application/vnd.adobe.workflow",
    "biz": "text/xml",
    "bmp": "application/x-bmp",
    "bot": "application/x-bot",
    "c4t": "application/x-c4t",
    "c90": "application/x-c90",
    "cal": "application/x-cals",
    "cat": "application/vnd.ms-pki.seccat",
    "cdf": "application/x-netcdf",
    "cdr": "application/x-cdr",
    "cel": "application/x-cel",
    "cer": "application/x-x509-ca-cert",
    "cg4": "application/x-g4",
    "cgm": "application/x-cgm",
    "cit": "application/x-cit",
    "class": "java/*",
    "cml": "text/xml",
    "cmp": "application/x-cmp",
    "cmx": "application/x-cmx",
    "cot": "application/x-cot",
    "crl": "application/pkix-crl",
    "crt": "application/x-x509-ca-cert",
    "csi": "application/x-csi",
    "css": "text/css",
    "cut": "application/x-cut",
    "dbf": "application/x-dbf",
    "dbm": "application/x-dbm",
    "dbx": "application/x-dbx",
    "dcd": "text/xml",
    "dcx": "application/x-dcx",
    "der": "application/x-x509-ca-cert",
    "dgn": "application/x-dgn",
    "dib": "application/x-dib",
    "dll": "application/x-msdownload",
    "doc": "application/msword",
    "dot": "application/msword",
    "drw": "application/x-drw",
    "dtd": "text/xml",
    "dwf": "application/x-dwf",
    "dwg": "application/x-dwg",
    "dxb": "application/x-dxb",
    "dxf": "application/x-dxf",
    "edn": "application/vnd.adobe.edn",
    "emf": "application/x-emf",
    "eml": "message/rfc822",
    "ent": "text/xml",
    "epi": "application/x-epi",
    "eps": "application/postscript",
    "etd": "application/x-ebx",
    "exe": "application/x-msdownload",
    "fax": "image/fax",
    "fdf": "application/vnd.fdf",
    "fif": "application/fractals",
    "fo": "text/xml",
    "frm": "application/x-frm",
    "g4": "application/x-g4",
    "gbr": "application/x-gbr",
    # "": "application/x-",
    "gif": "image/gif",
    "gl2": "application/x-gl2",
    "gp4": "application/x-gp4",
    "hgl": "application/x-hgl",
    "hmr": "application/x-hmr",
    "hpg": "application/x-hpgl",
    "hpl": "application/x-hpl",
    "hqx": "application/mac-binhex40",
    "hrf": "application/x-hrf",
    "hta": "application/hta",
    "htc": "text/x-component",
    "htm": "text/html",
    "html": "text/html",
    "htt": "text/webviewhtml",
    "htx": "text/html",
    "icb": "application/x-icb",
    "ico": "application/x-ico",
    "iff": "application/x-iff",
    "ig4": "application/x-g4",
    "igs": "application/x-igs",
    "iii": "application/x-iphone",
    "img": "application/x-img",
    "ins": "application/x-internet-signup",
    "isp": "application/x-internet-signup",
    "IVF": "video/x-ivf",
    "java": "java/*",
    "jfif": "image/jpeg",
    "jpe": "application/x-jpe",
    "jpeg": "image/jpeg",
    "jpg": "application/x-jpg",
    "js": "application/x-javascript",
    "jsp": "text/html",
    "la1": "audio/x-liquid-file",
    "lar": "application/x-laplayer-reg",
    "latex": "application/x-latex",
    "lavs": "audio/x-liquid-secure",
    "lbm": "application/x-lbm",
    "lmsff": "audio/x-la-lms",
    "ls": "application/x-javascript",
    "ltr": "application/x-ltr",
    "m1v": "video/x-mpeg",
    "m2v": "video/x-mpeg",
    "m3u": "audio/mpegurl",
    "m4e": "video/mpeg4",
    "mac": "application/x-mac",
    "man": "application/x-troff-man",
    "math": "text/xml",
    "mdb": "application/x-mdb",
    "mfp": "application/x-shockwave-flash",
    "mht": "message/rfc822",
    "mhtml": "message/rfc822",
    "mi": "application/x-mi",
    "mid": "audio/mid",
    "midi": "audio/mid",
    "mil": "application/x-mil",
    "mml": "text/xml",
    "mnd": "audio/x-musicnet-download",
    "mns": "audio/x-musicnet-stream",
    "mocha": "application/x-javascript",
    "movie": "video/x-sgi-movie",
    "mp1": "audio/mp1",
    "mp2": "audio/mp2",
    "mp2v": "video/mpeg",
    "mp3": "audio/mp3",
    "mp4": "video/mpeg4",
    "mpa": "video/x-mpg",
    "mpd": "application/vnd.ms-project",
    "mpe": "video/x-mpeg",
    "mpeg": "video/mpg",
    "mpg": "video/mpg",
    "mpga": "audio/rn-mpeg",
    "mpp": "application/vnd.ms-project",
    "mps": "video/x-mpeg",
    "mpt": "application/vnd.ms-project",
    "mpv": "video/mpg",
    "mpv2": "video/mpeg",
    "mpw": "application/vnd.ms-project",
    "mpx": "application/vnd.ms-project",
    "mtx": "text/xml",
    "mxp": "application/x-mmxp",
    "net": "image/pnetvue",
    "nrf": "application/x-nrf",
    "nws": "message/rfc822",
    "odc": "text/x-ms-odc",
    "out": "application/x-out",
    "p10": "application/pkcs10",
    "p12": "application/x-pkcs12",
    "p7b": "application/x-pkcs7-certificates",
    "p7c": "application/pkcs7-mime",
    "p7m": "application/pkcs7-mime",
    "p7r": "application/x-pkcs7-certreqresp",
    "p7s": "application/pkcs7-signature",
    "pc5": "application/x-pc5",
    "pci": "application/x-pci",
    "pcl": "application/x-pcl",
    "pcx": "application/x-pcx",
    "pdf": "application/pdf",
    "pdx": "application/vnd.adobe.pdx",
    "pfx": "application/x-pkcs12",
    "pgl": "application/x-pgl",
    "pic": "application/x-pic",
    "pko": "application/vnd.ms-pki.pko",
    "pl": "application/x-perl",
    "plg": "text/html",
    "pls": "audio/scpls",
    "plt": "application/x-plt",
    "png": "application/x-png",
    "pot": "application/vnd.ms-powerpoint",
    "ppa": "application/vnd.ms-powerpoint",
    "ppm": "application/x-ppm",
    "pps": "application/vnd.ms-powerpoint",
    "ppt": "application/x-ppt",
    "pr": "application/x-pr",
    "prf": "application/pics-rules",
    "prn": "application/x-prn",
    "prt": "application/x-prt",
    "ps": "application/postscript",
    "ptn": "application/x-ptn",
    "pwz": "application/vnd.ms-powerpoint",
    "r3t": "text/vnd.rn-realtext3d",
    "ra": "audio/vnd.rn-realaudio",
    "ram": "audio/x-pn-realaudio",
    "ras": "application/x-ras",
    "rat": "application/rat-file",
    "rdf": "text/xml",
    "rec": "application/vnd.rn-recording",
    "red": "application/x-red",
    "rgb": "application/x-rgb",
    "rjs": "application/vnd.rn-realsystem-rjs",
    "rjt": "application/vnd.rn-realsystem-rjt",
    "rlc": "application/x-rlc",
    "rle": "application/x-rle",
    "rm": "application/vnd.rn-realmedia",
    "rmf": "application/vnd.adobe.rmf",
    "rmi": "audio/mid",
    "rmj": "application/vnd.rn-realsystem-rmj",
    "rmm": "audio/x-pn-realaudio",
    "rmp": "application/vnd.rn-rn_music_package",
    "rms": "application/vnd.rn-realmedia-secure",
    "rmvb": "application/vnd.rn-realmedia-vbr",
    "rmx": "application/vnd.rn-realsystem-rmx",
    "rnx": "application/vnd.rn-realplayer",
    "rp": "image/vnd.rn-realpix",
    "rpm": "audio/x-pn-realaudio-plugin",
    "rsml": "application/vnd.rn-rsml",
    "rt": "text/vnd.rn-realtext",
    "rtf": "application/x-rtf",
    "rv": "video/vnd.rn-realvideo",
    "sam": "application/x-sam",
    "sat": "application/x-sat",
    "sdp": "application/sdp",
    "sdw": "application/x-sdw",
    "sit": "application/x-stuffit",
    "slb": "application/x-slb",
    "sld": "application/x-sld",
    "slk": "drawing/x-slk",
    "smi": "application/smil",
    "smil": "application/smil",
    "smk": "application/x-smk",
    "snd": "audio/basic",
    "sol": "text/plain",
    "sor": "text/plain",
    "spc": "application/x-pkcs7-certificates",
    "spl": "application/futuresplash",
    "spp": "text/xml",
    "ssm": "application/streamingmedia",
    "sst": "application/vnd.ms-pki.certstore",
    "stl": "application/vnd.ms-pki.stl",
    "stm": "text/html",
    "sty": "application/x-sty",
    "svg": "text/xml",
    "swf": "application/x-shockwave-flash",
    "tdf": "application/x-tdf",
    "tg4": "application/x-tg4",
    "tga": "application/x-tga",
    "tiff": "image/tiff",
    "tld": "text/xml",
    "top": "drawing/x-top",
    "torrent": "application/x-bittorrent",
    "tsd": "text/xml",
    "txt": "text/plain",
    "uin": "application/x-icq",
    "uls": "text/iuls",
    "vcf": "text/x-vcard",
    "vda": "application/x-vda",
    "vdx": "application/vnd.visio",
    "vml": "text/xml",
    "vpg": "application/x-vpeg005",
    "vsd": "application/x-vsd",
    "vss": "application/vnd.visio",
    "vst": "application/x-vst",
    "vsw": "application/vnd.visio",
    "vsx": "application/vnd.visio",
    "vtx": "application/vnd.visio",
    "vxml": "text/xml",
    "wav": "audio/wav",
    "wax": "audio/x-ms-wax",
    "wb1": "application/x-wb1",
    "wb2": "application/x-wb2",
    "wb3": "application/x-wb3",
    "wbmp": "image/vnd.wap.wbmp",
    "wiz": "application/msword",
    "wk3": "application/x-wk3",
    "wk4": "application/x-wk4",
    "wkq": "application/x-wkq",
    "wks": "application/x-wks",
    "wm": "video/x-ms-wm",

YunPan/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import UploadFile


def file_valid(value):
    file_size = value.size
    if file_size > 256 * 1024 * 1024:  # 256 MB
        raise ValidationError("文件过大")


class UploadFileForm(forms.Form):
    upload = forms.FileField(validators=[file_valid])
    file_type = forms.ChoiceField(choices=UploadFile.file_type_choices)

YunPan/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, StreamingHttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from urllib.parse import quote
from django.db.models import Q

from .models import UploadFile, ContentType
from .forms import UploadFileForm


def index(request):
    return render(request, 'YunPan/index.html')


def public(request):
    files = UploadFile.objects.filter(Q(file_type='public') | Q(file_type='media'))[::-1]
    return render(request, 'YunPan/public.html', {'files': files})


@login_required
def private(request):
    files = UploadFile.objects.filter(user=request.user)[::-1]
    return render(request, 'YunPan/private.html', {'files': files})


@login_required
def change_file_type(request, pk):
    file = UploadFile.objects.get(user=request.user, id=pk)
    if file.file_type == 'public':
        file.file_type = 'private'
    elif file.file_type == 'private':
        file.file_type = 'public'
    file.save()
    return render(request, 'YunPan/message.html', {'message': '移动成功'})


@login_required
def delete_file(request, pk):
    file = UploadFile.objects.get(user=request.user, id=pk)
    file.upload.delete()
    file.delete()
    return render(request, 'YunPan/message.html', {'message': '删除成功'})


@login_required
def download_private_file(request, pk):
    file = UploadFile.objects.get(user=request.user, id=pk)

    def file_iterator(chunk_size=512):
        while True:
            c = file.upload.read(chunk_size)
            if c:
                yield c
            else:
                break

    response = StreamingHttpResponse(file_iterator())
    response['Content-Type'] = ContentType.get(file.upload.name.split('.')[-1], 'application/octet-stream')
    response['Content-Disposition'] = 'attachment;filename="%s"' % quote(file.upload.name.split('/')[-1])
    return response


def download_file(request, pk):
    file = UploadFile.objects.get(id=pk)
    if file.file_type != 'public':
        return render(request, 'YunPan/message.html', {'message': '拒绝访问'})

    def file_iterator(chunk_size=512):
        while True:
            c = file.upload.read(chunk_size)
            if c:
                yield c
            else:
                break

    response = StreamingHttpResponse(file_iterator())
    response['Content-Type'] = ContentType.get(file.upload.name.split('.')[-1], 'application/octet-stream')
    response['Content-Disposition'] = 'attachment;filename="%s"' % quote(file.upload.name.split('/')[-1])
    return response


@login_required
def upload_file(request):
    if request.method != 'POST':
        form = UploadFileForm()
    else:
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = UploadFile(user=request.user, upload=form.cleaned_data['upload'],
                              file_type=form.cleaned_data['file_type'])
            file.save()
            return render(request, 'YunPan/message.html', {'message': '上传成功！'})
    return render(request, 'YunPan/upload_file.html', {'form': form})


def login(request):
    redirect_to = request.GET.get('next', '/')
    if request.method != 'POST':
        form = AuthenticationForm()
    else:
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.user_cache)
            return HttpResponseRedirect(redirect_to)
    return render(request, 'YunPan/login.html', {'form': form})


def register(request):
    return render(request, 'YunPan/message.html', {'message': '请先登录后注册'})


@login_required()
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('YunPan:index'))

YunPan/templates/YunPan/header.html
<!DOCTYPE html>
<html lang="cn-zh">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} 我的云盘 {% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"/>

    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<body>
<style>
    .mix {
        padding: 0;
        z-index: 1;
    }

    .mix, .mix > #bg {
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
    }

    .mix > #content {
        width: 100%;
        text-align: center;
        position: absolute;
        z-index: 2;
        top: 48%;
        -webkit-transform: translateY(-50%);
        -moz-transform: translateY(-50%);
        -ms-transform: translateY(-50%);
        transform: translateY(-50%);
    }
</style>
{% block body_top %}
{% endblock %}
<div class="container" style="width: 100%; height: 100%;">
    <div class="row-fluid">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target="#yp-navbar-collapse">
                        <span class="sr-only">Navbar</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        <span class="icon iconfont">YunPan</span></a>
                </div>
                <div class="collapse navbar-collapse" id="yp-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'YunPan:public' %}">公共区域</a></li>
                        <li><a href="{% url 'YunPan:private' %}">我的文件</a></li>
                        <li><a href="{% url 'YunPan:upload' %}">上传文件</a></li>
                        <li><a href="/media/" target="_blank">媒体文件</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                                <li><a href="/admin/" target="_blank"><span
                                        class="glyphicon glyphicon-user"></span> {{ user.username }}
                                </a>
                                    {% else %}
                                <li><a href="/"><span class="glyphicon glyphicon-user"></span> {{ user.username }}</a>
                            {% endif %}
                        </li>
                            <li><a href="{% url 'YunPan:logout' %}"><span class="glyphicon glyphicon-log-out"></span> 退出</a>
                            </li>
                        {% else %}
                            <li><a href="{% url 'YunPan:login' %}"><span class="glyphicon glyphicon-log-in"></span>
                                登录</a>
                            </li>
                            <li><a href="{% url 'YunPan:register' %}"><span class="glyphicon glyphicon-user"></span> 注册</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div style="height: 50px;"></div>
        <div class="mix">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

YunPan/templates/YunPan/index.html
{% extends 'YunPan/header.html' %}
{% block body %}
    <div id="content">
    </div>
{% endblock %}

YunPan/templates/YunPan/message.html
{% extends 'YunPan/header.html' %}
{% block body %}
    <div id="content">
        <div class="row">
            <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-2 col-xs-12 col-xs-offset-0">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h4><span class="glyphicon glyphicon-pencil"></span>&nbsp;Message
                        </h4>
                    </div>
                    <div class="panel-body">
                        <div id="alert-area">
                            <h4 style="text-align: center;">{{ message }}</h4>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

YunPan/templates/YunPan/private.html
{% extends 'YunPan/header.html' %}
{% block body %}
    <style>
        .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
            vertical-align: top;
        }

        .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td {
            vertical-align: middle;
        }

        #contest-list-table .form-group {
            margin-bottom: 0;
        }

        .main-bar {
            margin: 16px 0;
        }
    </style>
    <div id="blank" style="height: 50px;"></div>
    <div class="container">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>文件</th>
                <th>大小</th>
                <th>上传时间</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody class="vertical-middle">
            {% for file in files %}
                <tr>
                    <td name="file_name">{{ file.upload.name }}</td>
                    <td name="file_size">{{ file.upload.size }}</td>
                    <td>{{ file.upload_time }}</td>
                    <td>
                        <a href="{% url 'YunPan:download' pk=file.id %}" style="color:#fff">
                            <button class="btn btn-info">下载</button>
                        </a>
                        {% if file.file_type != 'media' %}
                            {% if file.file_type == 'public' %}
                                <button onclick="move_file({{ file.id }})" class="btn btn-info"
                                        id="file_type_{{ file.id }}">公共
                                </button>
                            {% else %}
                                <button onclick="move_file({{ file.id }})" class="btn btn-warning"
                                        id="file_type_{{ file.id }}">私有
                                </button>
                            {% endif %}
                        {% endif %}
                        <button onclick="delete_file({{ file.id }})" class="btn btn-danger">删除</button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        $("[name='file_name']").each(function () {
            this.innerText = this.innerText.split('/').pop();
        });

        function formatFileSize(fileSize) {
            if (fileSize < 1024) {
                return fileSize + 'B';
            } else if (fileSize < (1024 * 1024)) {
                var temp = fileSize / 1024;
                temp = temp.toFixed(2);
                return temp + 'KB';
            } else if (fileSize < (1024 * 1024 * 1024)) {
                var temp = fileSize / (1024 * 1024);
                temp = temp.toFixed(2);
                return temp + 'MB';
            } else {
                var temp = fileSize / (1024 * 1024 * 1024);
                temp = temp.toFixed(2);
                return temp + 'GB';
            }
        }

        $("[name='file_size").each(function () {
            this.innerText = formatFileSize(this.innerText / 1);
        })

        function move_file(id) {
            $.get("/move/" + id + "/", function (rst, state) {
                if (state === 'success') {
                    var this_file_type = $("#file_type_" + id);
                    if (this_file_type.text().indexOf('私有') !== -1) {
                        this_file_type.text('公共');
                        this_file_type.css('background-color', '#5bc0de');
                        this_file_type.css('border-color', '#46b8da');
                    } else {
                        this_file_type.text('私有');
                        this_file_type.css('background-color', '#f0ad4e');
                        this_file_type.css('border-color', '#eea236');
                    }
                }
            })
        }

        function delete_file(id) {
            if (!confirm("您确定删除此文件吗？"))
                return;
            $.get("/delete/" + id + "/", function (rst, state) {
                if (state === 'success') {
                    location.reload();
                }
            })
        }

    </script>
{% endblock %}

YunPan/templates/YunPan/public.html
{% extends 'YunPan/header.html' %}
{% block body_top %}
    <div class="modal fade" id="view" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="view_title">View</h4>
                </div>
                <div class="modal-body" id="view_body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block body %}
    <style>
        .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
            vertical-align: top;
        }

        .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td {
            vertical-align: middle;
        }

        #contest-list-table .form-group {
            margin-bottom: 0;
        }

        .main-bar {
            margin: 16px 0;
        }
    </style>
    <div id="blank" style="height: 50px;"></div>
    <div class="container">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>文件</th>
                <th>大小</th>
                <th>上传用户</th>
                <th>上传时间</th>
            </tr>
            </thead>
            <tbody class="vertical-middle">
            {% for file in files %}
                <tr>
                    <td><a href="{% url 'YunPan:file' pk=file.id %}" name="file_name">{{ file.upload.name }}</a>
                        {% if file.file_type == 'media' %}
                            <button class="btn btn-sm"
                                    onclick="view_media('{{ file.upload.url }}', '{{ file.upload.name }}')">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                        {% endif %}
                    </td>
                    <td name="file_size">{{ file.upload.size }}</td>
                    <td>{{ file.user.username }}</td>
                    <td>{{ file.upload_time }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        $("[name='file_name']").each(function () {
            this.innerText = this.innerText.split('/').pop();
        });

        function formatFileSize(fileSize) {
            if (fileSize < 1024) {
                return fileSize + 'B';
            } else if (fileSize < (1024 * 1024)) {
                var temp = fileSize / 1024;
                temp = temp.toFixed(2);
                return temp + 'KB';
            } else if (fileSize < (1024 * 1024 * 1024)) {
                var temp = fileSize / (1024 * 1024);
                temp = temp.toFixed(2);
                return temp + 'MB';
            } else {
                var temp = fileSize / (1024 * 1024 * 1024);
                temp = temp.toFixed(2);
                return temp + 'GB';
            }
        }

        $("[name='file_size").each(function () {
            this.innerText = formatFileSize(this.innerText / 1);
        });

        var img_type = ['bmp', 'jpg', 'png', 'tiff', 'gif', 'webp'];
        var audio_type = ['ogg', 'mp3', 'wav'];
        var video_type = ['mp4', 'ogg', 'webm'];

        function view_media(url, name) {
            $("#view_title").text(name.split('/').pop());
            var file_type = url.split('.').pop().toLowerCase();
            var view_node = '';
            if ($.inArray(file_type, img_type) >= 0) {
                view_node = '<img src="' + url + '" width=567px></img>';
            }
            else if ($.inArray(file_type, video_type) >= 0) {
                view_node = '<video src="' + url + '" autoplay width="567px" controls></video>';
            }
            else if ($.inArray(file_type, audio_type) >= 0) {
                view_node = '<audio src="' + url + '" autoplay width="567px" controls></audio>';
            }
            $("#view_body").html(view_node);
            $("#view").modal('show');
        }
    </script>
{% endblock %}